/**
 * 构建脚本：将 Chart.js 打包为内联字符串
 * 用于生成自包含的 HTML 报告
 */
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');

// Chart.js 路径
const chartjsPath = join(rootDir, 'node_modules/chart.js/dist/chart.umd.js');
const outputPath = join(rootDir, 'src/utils/html-export/chartjs-inline.ts');

function generate() {
  if (!existsSync(chartjsPath)) {
    console.error('Chart.js not found. Please run npm install first.');
    process.exit(1);
  }

  const chartjsCode = readFileSync(chartjsPath, 'utf-8');

  // 转义特殊字符用于模板字符串
  const escaped = chartjsCode
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\${/g, '\\${');

  const output = `// Auto-generated file. Do not edit manually.
// Generated by scripts/generate-chartjs-inline.ts

export const CHARTJS_INLINE = \`${escaped}\`;
`;

  writeFileSync(outputPath, output, 'utf-8');
  console.log('Generated chartjs-inline.ts');
}

generate();
